---
openapi: 3.0.1
info:
  title: API for HelloworldApplication
  version: unknown
paths:
  "/greeting":
    get:
      operationId: greeting
      parameters:
      - name: name
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: Default response
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/Greeting"
components:
  schemas:
    Greeting:
      type: object
      properties:
        id:
          type: integer
          format: int64
        content:
          type: string

